# Shallow Neural Network in Keras

Build a shallow neural network to classify MNIST digits

#### Set seed for reproducibility

In [1]:
import numpy as np
np.random.seed(42)

#### Load dependencies

In [2]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

Using TensorFlow backend.


#### Load data

In [3]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11501568/11490434 [==============================] - 41s 4us/step


In [4]:
X_train.shape

(60000, 28, 28)

In [5]:
y_train.shape

(60000,)

In [6]:
y_train[0:99]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0, 9,
       1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9, 3, 9,
       8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5, 6, 1, 0,
       0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9, 0, 4, 6, 7,
       4, 6, 8, 0, 7, 8, 3], dtype=uint8)

In [8]:
X_test.shape

(10000, 28, 28)

In [9]:
X_test[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [9]:
y_test.shape

(10000,)

In [10]:
y_test[0]

7

#### Preprocess data

In [14]:
# Convert 'darkness' value of each pixel from 0 - 255 to 0 -1

In [10]:
X_train = X_train.reshape(60000, 784).astype('float32')
X_test = X_test.reshape(10000, 784).astype('float32')

In [11]:
X_train /= 255
X_test /= 255

In [12]:
X_test[0]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [15]:
# Convert to one hot encoding

In [16]:
n_classes = 10
y_train = keras.utils.to_categorical(y_train, n_classes)
y_test = keras.utils.to_categorical(y_test, n_classes)

In [17]:
y_test[0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.])

#### Design neural network architecture

In [18]:
model = Sequential()
model.add(Dense(64, activation='sigmoid', input_shape=(784,)))
model.add(Dense(10, activation='softmax'))

In [19]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


In [18]:
(64*784)

50176

In [19]:
(64*784)+64

50240

In [20]:
(10*64)+10

650

#### Configure model

In [20]:
model.compile(loss='mean_squared_error', optimizer=SGD(lr=0.01), metrics=['accuracy'])

#### Train!

In [22]:
model.fit(X_train, y_train, batch_size=128, epochs=200, verbose=1, validation_data=(X_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0891 - acc: 0.2709 - val_loss: 0.0889 - val_acc: 0.2716
Epoch 2/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0888 - acc: 0.2907 - val_loss: 0.0886 - val_acc: 0.2878
Epoch 3/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0884 - acc: 0.3023 - val_loss: 0.0883 - val_acc: 0.3020
Epoch 4/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0881 - acc: 0.3097 - val_loss: 0.0879 - val_acc: 0.3091
Epoch 5/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0877 - acc: 0.3143 - val_loss: 0.0876 - val_acc: 0.3145
Epoch 6/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0874 - acc: 0.3176 - val_loss: 0.0872 - val_acc: 0.3185
Epoch 7/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0871 - acc: 0.3204 - val_loss: 0.0869 - 

60000/60000 [==============================] - 1s 21us/step - loss: 0.0642 - acc: 0.6117 - val_loss: 0.0637 - val_acc: 0.6163
Epoch 60/200
60000/60000 [==============================] - 1s 20us/step - loss: 0.0638 - acc: 0.6150 - val_loss: 0.0632 - val_acc: 0.6188
Epoch 61/200
60000/60000 [==============================] - 1s 20us/step - loss: 0.0633 - acc: 0.6188 - val_loss: 0.0627 - val_acc: 0.6222
Epoch 62/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0629 - acc: 0.6220 - val_loss: 0.0623 - val_acc: 0.6253
Epoch 63/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0624 - acc: 0.6253 - val_loss: 0.0618 - val_acc: 0.6277
Epoch 64/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0620 - acc: 0.6286 - val_loss: 0.0613 - val_acc: 0.6307
Epoch 65/200
60000/60000 [==============================] - 1s 21us/step - loss: 0.0615 - acc: 0.6317 - val_loss: 0.0609 - val_acc: 0.6337
Epoch 66/200
60000/60000 [==============

Epoch 118/200
60000/60000 [==============================] - 1s 20us/step - loss: 0.0421 - acc: 0.7745 - val_loss: 0.0411 - val_acc: 0.7851
Epoch 119/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0418 - acc: 0.7766 - val_loss: 0.0409 - val_acc: 0.7867
Epoch 120/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0415 - acc: 0.7782 - val_loss: 0.0406 - val_acc: 0.7883
Epoch 121/200
60000/60000 [==============================] - 1s 21us/step - loss: 0.0412 - acc: 0.7800 - val_loss: 0.0403 - val_acc: 0.7891
Epoch 122/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0410 - acc: 0.7818 - val_loss: 0.0401 - val_acc: 0.7909
Epoch 123/200
60000/60000 [==============================] - 1s 17us/step - loss: 0.0407 - acc: 0.7837 - val_loss: 0.0398 - val_acc: 0.7931
Epoch 124/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0405 - acc: 0.7855 - val_loss: 0.0395 - val_acc: 0.7950
Epoch 125/200
60000/

60000/60000 [==============================] - 1s 18us/step - loss: 0.0305 - acc: 0.8496 - val_loss: 0.0295 - val_acc: 0.8578
Epoch 177/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0304 - acc: 0.8502 - val_loss: 0.0294 - val_acc: 0.8584
Epoch 178/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0303 - acc: 0.8506 - val_loss: 0.0292 - val_acc: 0.8589
Epoch 179/200
60000/60000 [==============================] - 1s 17us/step - loss: 0.0301 - acc: 0.8511 - val_loss: 0.0291 - val_acc: 0.8591
Epoch 180/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0300 - acc: 0.8518 - val_loss: 0.0290 - val_acc: 0.8590
Epoch 181/200
60000/60000 [==============================] - 1s 22us/step - loss: 0.0299 - acc: 0.8521 - val_loss: 0.0288 - val_acc: 0.8594
Epoch 182/200
60000/60000 [==============================] - 1s 21us/step - loss: 0.0297 - acc: 0.8527 - val_loss: 0.0287 - val_acc: 0.8599
Epoch 183/200
60000/60000 [=======

In [23]:
model.evaluate(X_test, y_test)

 9472/10000 [===========================>..] - ETA: 0s

[0.027176343995332718, 0.86580000000000001]